### ISSUE TITLE
confirmed not working on python 2.5

### ISSUE THREAD

**Issue by thepeskygeek** [dvdotsenko/git_http_backend.py#17]
Error:
 [thunderkittens]$ python ./git_http_backend.py --help
 Traceback (most recent call last):
   File "./git_http_backend.py", line 28, in <module>
     import io
 ImportError: No module named io
 [thunderkittens]$

**Comment by dvdotsenko** [comment]
Thx. I will update the readme. 

There is so much "2.6+" in git_http_backend.py" that it's hard for me to imagine a straight rewrite with 2.5 in mind. On top of that, install of 2.5.x on Windows 7, 64bit is too unfriendly to work against, complicating the testing.

On the flip side I do intend to get away completely from caching any data locally. This will get rid of dependency on IO module, but will likely leave fewer, but some 2.6-isms in the code.

I'll take a glance at making git_http_backend 2.5-compatible then.
